server:
  port: 8001

spring:
  application:
    name: MoiKiitos
  datasource:
    username: admin
    password: admin
#    url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:/home/victor/Documents/data/moikiitos
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database: h2
    hibernate.ddl-auto: none
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1.0
    table: schema_version


springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    operationsSorter: method